### ISSUE TITLE
Data source configuration UI does not accept custom string for Managed Secret

### ISSUE THREAD

**Issue by fridgepoet** [grafana/redshift-datasource#212]
**What happened**:
Data source configuration UI does not accept custom string for Managed Secret

![220327608-1aae03e1-01a5-4234-82de-25fca2538ae6](https://user-images.githubusercontent.com/4163034/220931118-5b8710ae-c8d0-4e04-8c1c-ed2eefe68f84.png)

**What you expected to happen**:
That field can accept a custom string, without relying on listing the secrets or Redshift clusters, etc

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to data source configuration page
2. Scroll down to Redshift Details > AWS Secrets Manager
3. Try to enter a custom string for Managed Secret and save it

**Anything else we need to know?**:

This would be an improvement for the UI. A workaround would be to define the configuration file oneself; here are some examples:

Workaround yaml configurations:

```
  - name: AWS Redshift with managed secret
    type: grafana-redshift-datasource
    uid: uid_goes_here
    jsonData:
      authType: keys
      defaultRegion: region_goes_here
      database: database_name_here
      useManagedSecret: true
      managedSecret:
        arn: arn_for_managed_secret_goes_here
        name: managed_secret_name
      clusterIdentifier: redshift-cluster-grafana
    secureJsonData:
      accessKey: access_key_goes_here
      secretKey: secret_key_goes_here
```

```
- name: AWS Redshift assume role with managed secret
  type: grafana-redshift-datasource
  uid: uid_goes_here
  jsonData:
    authType: keys
    defaultRegion: region_goes_here
    database: database_goes_here
    dbUser: database_user_goes_here
    useManagedSecret: true
    managedSecret:
      arn: arn_for_managed_secret_goes_here
      name: managed_secret_name_goes_here
    clusterIdentifier: cluster_identifier_goes_here
    assumeRoleArn: assume_role_arn_goes_here
  secureJsonData:
    accessKey: access_key_goes_here
    secretKey: secret_key_goes_here
  version: 1
```

**Environment**:
- Grafana version: ~9.4.0
- Plugin version: ~1.6.0
