### ISSUE TITLE
Docs - Verify minimal IAM Policy

### ISSUE THREAD

**Issue by andresmgot** [grafana/redshift-datasource#59]
It may be possible to reduce even further the scope of the `AmazonRedshiftReadOnlyAccess` Policy provides. In particular, a user reported that:

```
     Policies:
       - PolicyName: AllowRDSRead
         PolicyDocument:
           Version: “2012-10-17”
           Statement:
             - Sid: RDS
               Effect: Allow
               Action:
                 - “redshift-data:*”
                 - “redshift:GetClusterCredentials”
               Resource: “*”
```

Is (potentially) less scoped. We should verify:
 - [x] What `AmazonRedshiftReadOnlyAccess` give access to
 - [x] If the given policy actually give `write` access (~~which we don't want~~. It's necessary to give permissions to execute statements).
